### ISSUE TITLE
GA event tracking

### ISSUE THREAD

**Issue by crobinson42** [AmericanSolutions/company-www#36]
Add custom GA events:

- [x] click any link in the header/nav

- [x] click "schedule a call"

- [x] click on the phone number in contact section

- [x] click on the email in contact section
